name: Naive Bayes Classification

description: >
  This configuration file describes the Naive Bayes Classification pipeline 
  for a dataset of computer-related data. The pipeline includes data loading, 
  preprocessing, model training, and evaluation.

version: 1.0

dataset:
  path: '/content/computer.csv'
  features: 
    - column_index: 2
      description: 'Feature column 1'
    - column_index: 3
      description: 'Feature column 2'
    - column_index: 4
      description: 'Feature column 3'
  target: 
    column_index: -1
    description: 'Target column'

preprocessing:
  test_size: 0.20
  random_state: 1
  scaling: 
    type: 'StandardScaler'
  
model:
  type: 'GaussianNB'
  
evaluation:
  metrics:
    - type: 'accuracy_score'
    - type: 'confusion_matrix'

output:
  - predicted_values: 'y_pred'
  - actual_values: 'y_test'
  - accuracy: 'ac'
  - confusion_matrix: 'cm'
